### ISSUE TITLE
developer.honeywell.com not there?

### ISSUE THREAD

**Issue by drbytes** [bramkragten/lyric#5]
I'm trying to get a developer account but http://developer.honeywell.com looks pretty barren, there is no app deployed there. Has it been like this for a while, I only just tried it today (05 oct).

Maybe they are in the midst of deploying a new service.. I dunno.

**Comment by garnern2** [comment]
I can't access anything on that website at all. I came to see if others were having the same issue.

**Comment by drbytes** [comment]
it's developers.honeywell.com

**Comment by andreimarinescu** [comment]
Mistakenly, because of all the communication regarding HoneywellHome migrating to Resideo.com, I discovered and signed in to http://developer.resideo.com. Just leaving this here in case anyone else makes this mistake as well (that site seems to not be working, creating a new app just gets stuck in "awaiting approval").

**Comment by drbytes** [comment]
I was stuck there... in the approval .. for a while now. I signed up at the url prvided by @andreimarinescu, it seems to work, thx!

**Comment by andreimarinescu** [comment]
It works for signing up, but the app is stuck in approval. I'm also stuck in user approval on "developers.honeywell.com". Is there any website that actually works, or our new thermostats essentially locked in a walled garden? :)

**Comment by drbytes** [comment]
Yeh,... The app I added says it needs "approval". It's only been half an hour. I wonder if they actually have a human go trough it instead of an automated process. If so, it might happen during US office hours.

Bit of a pain getting this sorted.

**Comment by andreimarinescu** [comment]
I've been stuck in "needs approval" since Saturday. So if there's anyone looking at these requests, no-one acted on them during Monday office hours. I've also written emails to their support email address without any reply. Hopefully someone replies, but this is either painfully slow or no longer working at all.

**Comment by drbytes** [comment]
I opened a ticket on their website saturday and haven't received an answer yet. 
Pretty stupid of them not throwing more resources at this emerging home automation market..
IFTT works, though, but pretty useless for my case.

**Comment by drbytes** [comment]
Still pending, I mailed them on HoneywellAPISupport@honeywellhome.com 2-3 days ago and they have yet to respond. 

The T6 is going back into the box and Amazon.

**Comment by andreimarinescu** [comment]
Yeah, I'm really disappointed as well. I'm really regretting my decision. Sad part is that I already have everything mounted.

**Comment by andreimarinescu** [comment]
The developer portal is now back online. I was able to get my OAUTH credentials. I'm now getting the 500 error because of the newer hass version, looking to find a workaround for that in a few minutes.

**Comment by drbytes** [comment]
Yeh, I have had success getting a key/secret via the developer platform, its immediatly approved.
But I got to the internal server error as well. I changed the url to the /auth url instead of the /api url.
I then downloaded the files in some PR on git into custom_components and it threw another error at which point I just said F it, I have other things to do :)

Keep us posted, tho.. it'll help other people.

**Comment by andreimarinescu** [comment]
Smooth sailing for me so far. Downloaded said PR, uploaded to my Hassio deployment, configured in configuration.yaml and then added the integration after rebooting. All seems to be working correctly, it's just I'll want to modify this component so that it also exposes the current equipment status. I want to know if the heating is currently turned off or on, and the sensors exposed by default don't seem to offer this info.

**Comment by drbytes** [comment]
Perhaps I got an out of date PR, mind sharing which one you used? I only investigated it briefly tbh... the thing is sitting on the desk to be shipped back, I guess I should give it another try.

**Comment by andreimarinescu** [comment]
I've used this HA PR here - https://github.com/home-assistant/home-assistant/tree/92082b687a46c17a9a94a598b245728a8832b179/homeassistant/components/lyric

Generally, I've followed the guidelines in the HA Community thread tracking this issue: https://community.home-assistant.io/t/honeywell-lyric-thermostat/3520/632

Good luck!
